//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesOfActorsOfRepertoir
    {
        public int Actor { get; set; }
        public int Role { get; set; }
        public int Repertoire { get; set; }
    
        public virtual Repertoir Repertoir { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
